### ISSUE TITLE
Hamster Wheel Crash

### ISSUE THREAD

**Issue by brodyofhearts** [starfish-studios/Hamsters#15]
I have this mod running on a Forge 1.19.2 server and, for a while, things were fine. Recently it has began crashing a lot and it seems to be related with the hamsters, specifically them trying to enter a hamster wheel. No clue if there is some sort of mod conflict or issue from the host I'm using.

[crash-2024-03-24_04.07.27-server.txt](https://github.com/starfish-studios/Hamsters/files/14734351/crash-2024-03-24_04.07.27-server.txt)

**Comment by Eclipse-Sol** [comment]
I think I got the same crash here, Neruina can catch these exceptions.

```
[01:41:17] [Server thread/WARN]: Neruina caught an exception, see below for cause
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at com.starfish_studios.hamsters.entity.Hamster$HamsterGoToWheelGoal.method_6268(Hamster.java:708) ~[hamsters-fabric-1.0.3-1.20.1.jar:?]
	at net.minecraft.class_4135.method_6268(class_4135.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_1355.method_38849(class_1355.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:779) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2673) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.method_6007(class_1429.java:58) ~[client-intermediary.jar:?]
	at com.starfish_studios.hamsters.entity.Hamster.method_6007(Hamster.java:372) ~[hamsters-fabric-1.0.3-1.20.1.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[client-intermediary.jar:?]
	at com.starfish_studios.hamsters.entity.Hamster.method_5773(Hamster.java:357) ~[hamsters-fabric-1.0.3-1.20.1.jar:?]
	at net.minecraft.class_3218.observable$track(class_3218.java:20754) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.redirect$jle000$observable$onTickNonPassenger(class_3218.java:20770) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.mixinextras$bridge$accept$205(class_1937.java) ~[client-intermediary.jar:?]
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.1-fabric+1.20.1.jar:?]
	at net.minecraft.class_1937.wrapOperation$jij000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:16048) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$dhl000$carpet$modifiedRunLoop(MinecraftServer.java:20442) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
